wandb_version: 1

_wandb:
  desc: null
  value:
    python_version: 3.11.4
    cli_version: 0.15.10
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1696096573.096495
    t:
      1:
      - 1
      - 5
      - 53
      - 55
      2:
      - 1
      - 5
      - 53
      - 55
      3:
      - 2
      - 13
      - 23
      4: 3.11.4
      5: 0.15.10
      8:
      - 4
      - 5
population_size:
  desc: null
  value: '160'
n_generations:
  desc: null
  value: '25'
selection_rate:
  desc: null
  value: '0.3'
mutation_rate:
  desc: null
  value: '0.05'
increased_mutation_rate:
  desc: null
  value: '0.2'
num_elites:
  desc: null
  value: '16'
n_features:
  desc: null
  value: '141'
max_depth:
  desc: null
  value: '5'
depth_range:
  desc: null
  value: (1, 5)
latent_dim_range:
  desc: null
  value: (2, 128)
n_epochs:
  desc: null
  value: '15'
score_metric:
  desc: null
  value: <function silhouette_score at 0x12a688400>
parent_selection_method:
  desc: null
  value: roulette
crossover_method:
  desc: null
  value: two_point
clustering_algo:
  desc: null
  value: hdbscan
min_cluster_size_range:
  desc: null
  value: (2, 50)
learning_rate:
  desc: null
  value: '0.001'
batch_size:
  desc: null
  value: '64'
device:
  desc: null
  value: cpu
